# Generated by Django 6.0.6 on 2026-07-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_plans', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RotationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('crop_recommended', models.CharField(max_length=100)),
                ('crop_family', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_applied', models.BooleanField(default=False)),
                ('nitrogen_before', models.FloatField()),
                ('phosphorus_before', models.FloatField()),
                ('potassium_before', models.FloatField()),
                ('ph_before', models.FloatField()),
                ('nitrogen_after', models.FloatField()),
                ('phosphorus_after', models.FloatField()),
                ('potassium_after', models.FloatField()),
                ('ph_after', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rotation.rotationplan')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
    ]
