# Generated by Django 6.0.6 on 2026-09-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_setup_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Shown on your profile and in the navbar.', null=True, upload_to='profile_pictures/'),
        ),
    ]
