# Generated by Django 6.0.6 on 2026-07-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='e.g., maize, beans, cassava', max_length=100)),
                ('stage', models.CharField(choices=[('Preparation', 'Land Preparation'), ('Planting', 'Planting & Spacing'), ('Fertilizer', 'Nutrient & Fertilizer'), ('Weeding', 'Weeding'), ('Pests', 'Pest Control'), ('Diseases', 'Disease Management'), ('Harvest', 'Harvesting'), ('Storage', 'Post-Harvest Storage')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Crop Advisories',
                'unique_together': {('crop_name', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='SeasonTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='farms.farm')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
