# Generated by Django 6.0.6 on 2026-07-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('size_acres', models.FloatField(help_text='Size of the farm in acres')),
                ('soil_type', models.CharField(choices=[('Loam', 'Loam'), ('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Silt', 'Silt'), ('Peat', 'Peat'), ('Chalky', 'Chalky'), ('Volcanic', 'Volcanic')], default='Loam', max_length=100)),
                ('latitude', models.FloatField(blank=True, help_text='GPS Latitude (optional)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='GPS Longitude (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('nitrogen', models.FloatField(help_text='Nitrogen (N) value in mg/kg')),
                ('phosphorus', models.FloatField(help_text='Phosphorus (P) value in mg/kg')),
                ('potassium', models.FloatField(help_text='Potassium (K) value in mg/kg')),
                ('ph', models.FloatField(help_text='Soil pH level (3.5 - 8.5)')),
                ('temperature', models.FloatField(help_text='Average temperature in °C')),
                ('humidity', models.FloatField(help_text='Average relative humidity in %')),
                ('rainfall', models.FloatField(help_text='Average seasonal rainfall in mm')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='farms.farm')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
