# Generated by Django 6.0.6 on 2026-07-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('yield_rating', models.CharField(choices=[('Good', 'Good Yield (Expected or higher)'), ('Average', 'Average Yield'), ('Poor', 'Poor Yield'), ('Failed', 'Crop Failure / Minimal Yield')], max_length=20)),
                ('satisfaction_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('residue_management', models.CharField(choices=[('Incorporated', 'Incorporated back into the soil (Green manure)'), ('Removed', 'Removed / Burned / Fed to livestock')], max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
